### ISSUE TITLE
model init breaks on latest jax install

### ISSUE THREAD

**Issue by pranavsubramani** [deepmind/dm-haiku#121]
GPU - NVIDIA 1050 Ti
CUDA Version - 10.2
Jaxlib version - 0.1.64
Haiku Version - 0.0.4dev
Operating System - PopOS 20.04 

Recently, I did a fresh install of some components and JAX works perfectly on the GPU and it perfectly finds the GPU. But when I use haiku, the model init seems to break.

In particular, I have the following line in my code:

```
init_params = model.init(key, train_data[:args.batch_sz, :args.d])
```

And I receive the most obscure error:

```
2021-04-02 00:45:25.279644: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc:339] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2021-04-02 00:45:25.279673: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:1960] Execution of replica 0 failed: Unimplemented: DNN library is not found.
```

Any insight into why this might be happening?

**Comment by tomhennigan** [comment]
Hi @pranavsubramani it seems likely to me that this is a general issue with your JAX installation. Do you have [CuDNN](https://developer.nvidia.com/cudnn) installed?

I'd suggest checking you've followed https://github.com/google/jax#pip-installation closely and if you still have a broken install then google/jax#4920 and some other issues on the JAX repo should be helpful.

**Comment by pranavsubramani** [comment]
Hey @tomhennigan, it's actually a really strange issue -- I have JAX installed correctly, and flax works out of the box too.

**Comment by pranavsubramani** [comment]
Actually -- it seems like this is a convolution issue with XLA -- I did some more debugging and the feed forward model works, but for some reason, the convolution does not:

```
] Failed to determine best cudnn convolution algorithm: Internal: All algorithms tried for convolution %custom-call = (f32[50,14,14,16]{2,1,3,0}, u8[0]{0}) custom-call(f32[50,28,28,1]{2,1,3,0} %bitcast, f32[8,8,1,16]{1,0,2,3} %copy.4), window={size=8x8 stride=2x2 pad=3_3x3_3}, dim_labels=b01f_01io->b01f, custom_call_target="__cudnn$convForward", metadata={op_type="conv_general_dilated" op_name="conv_general_dilated[ batch_group_count=1\n                      dimension_numbers=ConvDimensionNumbers(lhs_spec=(0, 3, 1, 2), rhs_spec=(3, 2, 0, 1), out_spec=(0, 3, 1, 2))\n                      feature_group_count=1\n                      lhs_dilation=(1, 1)\n                      lhs_shape=(50, 28, 28, 1)\n                      padding=((3, 3), (3, 3))\n                      precision=None\n                      rhs_dilation=(1, 1)\n                      rhs_shape=(8, 8, 1, 16)\n                      window_strides=(2, 2) ]"}, backend_config="{\"algorithm\":\"0\",\"tensor_ops_enabled\":false,\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}" failed. Falling back to default algorithm. 
```

@tomhennigan -- do you have any insight into this? It's only the conv layer that breaks

**Comment by pranavsubramani** [comment]
Documenting here in case someone encounters the same issue -- the issue was that cudnn was not being recognized by JAX. Reinstalling is likely the easiest option.
